#ifndef SAILORCLIENT_GLOBAL_H
#define SAILORCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SAILORCLIENT_LIBRARY)
#  define SAILORCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAILORCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAILORCLIENT_GLOBAL_H
