#ifndef WEBSOCKETCLIENT_GLOBAL_H
#define WEBSOCKETCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WEBSOCKETCLIENT_LIBRARY)
#  define WEBSOCKETCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WEBSOCKETCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WEBSOCKETCLIENT_GLOBAL_H
